import 'dart:async';
import 'dart:convert';
import 'dart:math';
import 'dart:ui';

import 'package:cached_network_image/cached_network_image.dart';
import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:confetti/confetti.dart';
import 'package:crypto/crypto.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:image_picker/image_picker.dart';
import 'package:just_audio/just_audio.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:video_player/video_player.dart';

import 'core/constants/app_identity.dart';
import 'core/constants/default_learning_catalog.dart';
import 'core/utils/api_error_mapper.dart';
import 'core/utils/local_file_ops.dart';
import 'core/utils/local_media_widgets.dart';
import 'core/utils/media_source_helper.dart';
import 'database/collections/learning_material_collection.dart';
import 'database/isar_database_service.dart';
import 'models/app_local_models.dart';
import 'models/badge_definition.dart';
import 'repositories/badge_repository.dart';
import 'repositories/history_repository.dart';
import 'repositories/material_repository.dart';
import 'repositories/progress_repository.dart';
import 'repositories/theme_repository.dart';
import 'repositories/user_repository.dart';
import 'services/auth_service.dart';
import 'services/cloud_sync_service.dart';
import 'services/legacy_migration_service.dart';
import 'services/offline_bootstrap_service.dart';
import 'services/upload_service.dart';
import 'storage/local_storage_service.dart';

part 'src/models.dart';
part 'src/local_database.dart';
part 'src/theme_data.dart';
part 'src/learning_data.dart';
part 'src/app_state.dart';
part 'src/ui_helpers.dart';
part 'src/app_root.dart';
part 'src/auth_screen.dart';
part 'src/shell_main_screen.dart';
part 'src/learning_screens.dart';
part 'src/songs_screen.dart';
part 'src/account_screen.dart';
part 'src/teacher_dashboard.dart';
part 'src/screen_widgets.dart';
part 'src/badge_system.dart';
part 'src/badge_screen.dart';

const adminEmail = 'andibayu8310@gmail.com';

void main() => runApp(const ProviderScope(child: KhoirQuestApp()));
